### ISSUE TITLE
<not-authorized/> on valid password containing non-ASCII Unicode characters

### ISSUE THREAD

**Issue by linkmauve** [maranda/metronome#529] opened 2021-01-31 19:15 UTC
```xml
<failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl">                                    
  <not-authorized />                                                                  
  <text>Unable to authorize you with the authentication credentials you've sent</text>
</failure>                                                                            
```

The password contains characters such as U+202F and U+00AC, which might get wrongly stringprep’d for YunoHost’s LDAP thingy. It works when using plain ASCII.

**Comment by maranda** [comment] 2021-02-05 11:49
The problem is that Unicode is not prepped correctly either when passed to the backend from mod_auth_ldap2 or when inserted into the LDAP server by the YuNoHost management frontend, moving this to https://github.com/YunoHost/issues/issues/1729.

**Closed by maranda** 2021-02-05 11:49 UTC
Labels: invalid, need more info
